#! /bin/bash

#20171202 自动获取网卡和IPv6地址
#过滤回环和WiFi(设备首字母为w)
devs=`ifconfig | grep -o "^\w*" | grep -v -E '^(lo|[wW])'`
if [ `echo "$devs" | wc -l` -lt 2 ]
then
    echo "need 2 network cards"
    exit 1
fi

eth0=`echo $devs | awk '{print $1}'`
eth1=`echo $devs | awk '{print $2}'`
#有多个IPv6 Global地址,只取第一个
#直接在``两边添加()无法形成一个数组
IF1[0]=`ifconfig $eth0 | grep -o -P '\b[23][\w:]*(?=/)' | sed -n 1p`
IF2[0]=`ifconfig $eth1 | grep -o -P '\b[23][\w:]*(?=/)' | sed -n 1p`

NETWORK=`echo ${IF1[0]} | grep -o -P "^\w*(:\w*){3}"`"::"
ROUTER=$NETWORK"1"

if [ `id -u` -ne 0 ]
then
    echo "need sudo permission"
    exit 1
fi

if [ $# -lt 1 ]
then
    echo "$0 add | del | rule | route"
    exit 0
fi

if [ "$1" = "rule" ]
then
    ip -6 rule show
elif [ "$1" = "route" ]
then
    echo "show table ${eth0}"
    ip -6 route show table ${eth0}
    echo
    echo "show table ${eth1}"
    ip -6 route show table ${eth1}
elif [ "$1" = "add" -o "$1" = "del" ]
then
    if [ "$1" = "add" -a `ip -6 rule | wc -l` -gt 2 ]
    then
        echo "route has been established"
        exit 0
    fi
    if [ "$1" = "del" -a `ip -6 rule | wc -l` -eq 2 ]
    then
        echo -e "route \033[31mhas not\033[0m been established"
        exit 0
    fi

    for ipv6 in ${IF1[*]}
    do
        ip -6 rule "$1" from ${ipv6} table ${eth0}
    done

    for ipv6 in ${IF2[*]}
    do
        ip -6 rule "$1" from ${ipv6} table ${eth1}
    done

    ip -6 route "$1" ${NETWORK}/64 dev ${eth0} scope link table ${eth0}
    ip -6 route "$1" default via ${ROUTER} dev ${eth0} table ${eth0}

    ip -6 route "$1" ${NETWORK}/64 dev ${eth1} scope link table ${eth1}
    ip -6 route "$1" default via ${ROUTER} dev ${eth1} table ${eth1}
else
    echo "unknow command"
fi